### ISSUE TITLE
Whether hystrix will be supported?

### ISSUE THREAD

**Issue by SkyvenXiong** [bloritsch/DHaven.Faux#32]
this project is wonderful;but i have some questions.

1. steeltoe add a new feature circuitbreker .is it  in your roadmap?
2. like the asp.net routing mechanism. do you consider to use the service name and the method name as the default config to general the url ? 
3. do you consider to use dynamic proxy to implement your design.

**Comment by bloritsch** [comment]
1.  I have a bit of research to do with Hystrix support.  Is CircuitBreaker what the Steeltoe team calls it's support for Hystrix?

1. The [FauxClient] defines the name used for lookup in the discovery server.  The [Route] can be used to append any more to the base URL.  The Asp.Net MVC routing system is closer to what I modeled the attributes after, since this is about REST APIs.  You do have a fair amount of control over the URI generation.

1.  Do you have a specific use case for dynamic proxies?  I'm keen on keeping the library light weight, yet flexible.

**Comment by bloritsch** [comment]
From what I've read with the CircuitBreaker and Hystrix write-ups, I would have to come up with a way for you to define some really important things, like default values if the external service takes too long, timing threshold for timing out, etc.

While I think I can wrap each method with a set of generated Hystrix commands, but I'm going to need to play with it some to make sure I'm doing it right.

**Comment by bloritsch** [comment]
I'm working through the sample app, and if you handle the HystrixCommand yourself, then there are no changes required for DHaven.Faux.  The Steeltoe implementation doesn't have the attribute support that the Spring Boot counterpart does.  I'm going to spend some time with the Feign library to understand how it's generating the HystrixCommand instances.  I don't think it supports default values.

**Comment by bloritsch** [comment]
So I think I have a good idea on how to include this, and support fallback values.  There will need to be some changes in how I generate the classes, so I'm going to play with the generated code some.  There will necessarily be some changes to the class generator.

**Comment by bloritsch** [comment]
Bottom line answer: yes.

Issue #43 will track the implementation.
