### ISSUE TITLE
Euraka injection problem

### ISSUE THREAD

**Issue by honorduan** [bloritsch/DHaven.Faux#52]
I found that the incoming configuration was not used when generating the service, which led me to modify the eureka configuration with code without taking effect and without using the memory configuration.
So I recommend using the method ConfigureServices for the fauxcollection.cs file instead
Private static IServiceCollection ConfigureServices(IServiceCollection services, Type starterType)
{
Var config = FauxExtensions. Configuration;
If (config = = null)
{
Var builder = new ConfigurationBuilder()
SetBasePath (Directory. GetCurrentDirectory ())
AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
AddEnvironmentVariables ();
The config = builder. The Build ();
}
Services. AddLogging (logger = > logger. AddDebug () AddConfiguration (config));
Services. AddFaux (config, starterType);
Return services;
}
Then set the static variable public static IConfiguration Configuration in FauxExtensions.
I'm going to assign that to the AddFaux method
// the configured service collection
[SuppressMessage (" ReSharper ", "MemberCanBePrivate. Global")]
[SuppressMessage (" ReSharper ", "UnusedMethodReturnValue. Global")]
Public static IServiceCollection AddFaux(this IServiceCollection services, IConfiguration configuration,
Type starterType = null)
{
The Configuration = Configuration;
Return AddFaux (services, configuration, starterType? The Assembly?? The Assembly. GetEntryAssembly ());
}

**Comment by bloritsch** [comment]
Can you help me understand how you are using `FauxCollection` in your application?  It's meant to really only be used for standalone applications that are not using dependency injection.  It should work just fine for dependency injection based applications like ASP.Net MVC apps.

I want to understand your use case so that I can figure out if there is anything else that needs to change.

NOTE: if you use the ` character three times before and after a code block, it gets formatted in a way that is much easier to read.  See the [markdown quick-guide](https://guides.github.com/features/mastering-markdown/) code examples for more information.

**Comment by honorduan** [comment]
Um... This happens when I pass in a configuration that consists of the service.addfaux () method. And I'm not using appsettings for this configuration, I'm using code, which is the memory configuration that I'm using. At this time, I found that I could not successfully register, so I looked at the lower level and found that when I instantiated the service, you called appsettings.json configuration, not my memory configuration.

**Comment by bloritsch** [comment]
If you are using Dependency Injection (https://github.com/bloritsch/DHaven.Faux/wiki/Initialize-with-Dependency-Injection) then you should not be using `FauxCollection`.  The sole purpose of that is to handle the case where you aren't using the larger DI infrastructure.

I at least have an idea of what's going on, and I do need to allow `FauxCollection` to be created with your own Configuration.  I'll have to do a little refactoring then.

**Comment by bloritsch** [comment]
I added an optional `IConfiguration` parameter to FauxCollection's constructor.  That will allow you to initialize it with your own configuration.  I also added some more info in the XML docs so that it is clearer that FauxCollection should only be used if you have no other options.  Will be published with next release.
